name: CI - Build and Lint

on:
  push:
    branches:
      - main  # Executa no push para a branch main
  pull_request:
    branches:
      - main  # Executa em pull requests na branch main

jobs:
  build-and-test:
    name: Build, Lint, and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run Lint
        run: npm run lint

      - name: Build project
        run: npm run build